test:
  network: "emulator"
  name: Test
  description: >-
    To benchmark transferring tokens between accounts.
  workers:
    number: 1
  rounds:
    - label: 50 txns with 10tps
      description: >-
        Transfer Tokens between accounts.
      rateControl:  
        txNumber: 50
        tps: 20
    # - label: 50 txns with 5tps
    #   description: Test description for transfering money between accounts.
    #   rateControl:
    #     txNumber: 50
    #     tps: 5
    # - label: 50 txns with 10tps
    #   description: >-
    #     Transfer Tokens between accounts at a rate of 5 transaction per second.
    #   rateControl:
    #     txNumber: 50
    #     tps: 10
