scriptPath: "/path/to/script.cdc"
gasLimit: 100000
scriptArguments:
  amount:
    type: "UFix64"
    value: "1.234"
  recipient:
    type: "Address"
    value: "1ba7234d25ebb0c0"
payer:
  useSameAccount: true
  address: "xxxxxxxxxxxxxxxxx"
  privateKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
proposer:
  useSameAccount: true
  address: "xxxxxxxxxxxxxxxxx"
  privateKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
authorizer:
  useSameAccount: true
  address: "xxxxxxxxxxxxxxxxx"
  privateKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"