scriptPath: "script/sendFlow.cdc"
gasLimit: 1000000
scriptArguments:
  amount:
    name: "amount"
    type: "UFix64"
    value: "1.234"
  recipient:
    name: "recipient"
    type: "Address"
    value: "01cf0e2f2f715450"
payer:
  address: "f8d6e0586b0a20c7"
  privateKey: "bd674c5bccc5a43b61395cd886c291438c4a2592451b6c04e727959b77e3b1cc"
proposer:
  useSameAccount: true
  address: "0x1234567890abcdef"
  privateKey: "proposerprivatekey123"
  proposerKeyIndex: 0
authorizer:
  useSameAccount: true
  address: "0xabcdef1234567890"
  privateKey: "authorizerprivatekey123"